spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Indispensable pour PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Utilise 'create' une seule fois pour générer la table employe
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Empêche le crash si tu as des scripts d'initialisation
spring.jpa.defer-datasource-initialization=true

server.port=${PORT:8081}